pub(super) const REQUIRED_VISUAL_CONTRACT_DOC_MARKERS: &[(&str, &str)] = &[
    ("README.md", "size_px = 32.0"),
    ("README.md", "line_height_px = 44.0"),
    ("README.md", "background_opacity = 1.0"),
    ("README.md", "cursor_opacity = 1.0"),
    ("README.md", "selection_opacity = 1.0"),
    ("README.md", "surface_padding_px = 14"),
    ("README.md", "cell_spacing_px = 0"),
    ("README.md", "preset = \"gromaq-ghostty\""),
    ("README.md", "cargo run -- --theme-list"),
    ("README.md", "cargo run -- --theme-export gromaq-ghostty"),
    ("README.md", "cargo run -- --runtime-text-zoom-smoke"),
    ("README.md", "cargo run -- --theme-legibility-smoke"),
    ("README.md", "cargo run -- --theme-preview-snapshot"),
    ("README.md", "cargo run -- --theme-preview-config"),
    (
        "README.md",
        "cargo run -- --welcome-preview-snapshot target/gromaq-welcome-preview.ppm",
    ),
    ("README.md", "node images/avatar/generate.mjs --check"),
    ("README.md", "scripts/prove-welcome-preview.sh"),
    ("README.md", "scripts/prove-readme-welcome-preview.sh"),
    ("README.md", "avatar rows=17"),
    ("README.md", "selection opacity, before adopting it"),
    ("documentation/theme.md", "32 px font size"),
    ("documentation/theme.md", "44 px line height"),
    ("documentation/theme.md", "18 px automatic cell width"),
    ("documentation/theme.md", "background_opacity"),
    ("documentation/theme.md", "cursor_opacity"),
    ("documentation/theme.md", "selection_opacity"),
    ("documentation/theme.md", "built-in default is `14`"),
    ("documentation/theme.md", "cell_spacing_px"),
    ("documentation/theme.md", "Control/Super `+`"),
    ("documentation/theme.md", "Control/Super `0`"),
    (
        "documentation/theme.md",
        "`cargo run -- --runtime-text-zoom-smoke`",
    ),
    (
        "documentation/theme.md",
        "`cargo run -- --theme-legibility-smoke`",
    ),
    (
        "documentation/theme.md",
        "`cargo run -- --theme-preview-snapshot",
    ),
    (
        "documentation/theme.md",
        "`cargo run -- --theme-preview-config",
    ),
    (
        "documentation/theme.md",
        "`cargo run -- --welcome-preview-snapshot",
    ),
    (
        "documentation/theme.md",
        "`node images/avatar/generate.mjs --check`",
    ),
    ("documentation/theme.md", "scripts/prove-welcome-preview.sh"),
    ("documentation/theme.md", "gromaq --theme-list"),
    ("documentation/theme.md", "gromaq --theme-export"),
    ("documentation/theme.md", "gromaq --theme-preview-config"),
    (
        "documentation/theme.md",
        "gromaq --welcome-preview-snapshot",
    ),
    ("documentation/compatibility.md", "32/18/44 px"),
    ("documentation/compatibility.md", "37/21/51 px"),
    ("documentation/compatibility.md", "gromaq-ghostty"),
    (
        "documentation/compatibility.md",
        "--welcome-preview-snapshot <path>",
    ),
    (
        "documentation/compatibility.md",
        "scripts/prove-welcome-preview.sh",
    ),
    (
        "documentation/compatibility.md",
        "node images/avatar/generate.mjs --check",
    ),
    ("documentation/compatibility.md", "avatar color pixels"),
    (
        "documentation/compatibility.md",
        "input-to-render p95 budget ns: 10000000",
    ),
    (
        "documentation/compatibility.md",
        "runtime perf p95 smoke: ok",
    ),
    ("documentation/release.md", "36x17-sampled Braille avatar"),
    ("documentation/release.md", "36299 avatar color pixels"),
    ("documentation/release.md", "692 glyph quads"),
    ("documentation/release.md", "624624 atlas bytes"),
];

pub(super) const REQUIRED_RELEASE_DOC_MARKERS: &[(&str, &str)] = &[
    ("README.md", "GROMAQ_INSTALL_APP_BUNDLE=1"),
    ("README.md", "GROMAQ_DRY_RUN=1"),
    ("README.md", "GROMAQ_INSTALL_METHOD=release"),
    ("README.md", "GROMAQ_BIN_DIR"),
    ("README.md", "GROMAQ_VERIFY_CHECKSUMS=0"),
    ("README.md", "GROMAQ_CHECKSUM_EXTRA_FILES"),
    ("README.md", "packaging/arch/PKGBUILD"),
    ("README.md", "packaging/arch/.SRCINFO"),
    ("README.md", "packaging/arch/gromaq.install"),
    ("README.md", "arch-packaging"),
    ("README.md", "makepkg --nobuild"),
    ("README.md", "makepkg --noconfirm"),
    ("README.md", "pacman -U"),
    ("README.md", "scripts/prove-arch-package.sh"),
    ("README.md", "scripts/prove-debian-package.sh"),
    ("README.md", "scripts/prove-linux-release-install.sh"),
    ("README.md", "scripts/prove-github-release-install.sh"),
    ("README.md", "scripts/prove-current-host-compatibility.sh"),
    ("README.md", "GROMAQ_MACOS_APP_DIR"),
    (
        "README.md",
        "installer asset placement plus Linux tarball and Debian package assembly",
    ),
    (
        "README.md",
        "Debian `postinst`/`postrm` desktop refresh hooks",
    ),
    (
        "README.md",
        "Debian package install, `gromaq --version`, and installed-payload checks",
    ),
    ("README.md", "remote GitHub Actions release workflow"),
    (
        "README.md",
        "live tag-triggered GitHub Release asset publication",
    ),
    (
        "README.md",
        "live Linux release-method install from GitHub Release assets",
    ),
    (
        "README.md",
        "Linux desktop database refresh when `update-desktop-database` is available",
    ),
    ("README.md", "signed/notarized macOS app distribution"),
    ("documentation/release.md", "GROMAQ_INSTALL_APP_BUNDLE=1"),
    ("documentation/release.md", "GROMAQ_DRY_RUN=1"),
    ("documentation/release.md", "GROMAQ_INSTALL_METHOD=release"),
    ("documentation/release.md", "GROMAQ_BIN_DIR"),
    ("documentation/release.md", "GROMAQ_VERIFY_CHECKSUMS=0"),
    ("documentation/release.md", "GROMAQ_CHECKSUM_EXTRA_FILES"),
    ("documentation/release.md", "packaging/arch/PKGBUILD"),
    ("documentation/release.md", "packaging/arch/.SRCINFO"),
    ("documentation/release.md", "packaging/arch/gromaq.install"),
    ("documentation/release.md", "arch-packaging"),
    ("documentation/release.md", "makepkg --nobuild"),
    ("documentation/release.md", "makepkg --noconfirm"),
    ("documentation/release.md", "pacman -U"),
    ("documentation/release.md", "scripts/prove-arch-package.sh"),
    (
        "documentation/release.md",
        "scripts/prove-debian-package.sh",
    ),
    (
        "documentation/release.md",
        "scripts/prove-linux-release-install.sh",
    ),
    (
        "documentation/release.md",
        "scripts/prove-github-release-install.sh",
    ),
    (
        "documentation/compatibility.md",
        "scripts/prove-current-host-compatibility.sh",
    ),
    (
        "documentation/compatibility.md",
        "scripts/prove-current-host-compatibility.sh` passed on 2026-06-28 UTC",
    ),
    ("documentation/release.md", "GROMAQ_MACOS_APP_DIR"),
    (
        "documentation/release.md",
        "optional macOS app-bundle install path",
    ),
    (
        "documentation/release.md",
        "Debian `postinst` and `postrm` maintainer scripts",
    ),
    (
        "documentation/release.md",
        "Debian package install, `gromaq --version`, and installed-payload checks",
    ),
    ("documentation/release.md", "desktop-file-utils"),
    (
        "documentation/release.md",
        "tag-triggered GitHub Release publication path is configured locally",
    ),
    (
        "documentation/release.md",
        "Arch `PKGBUILD` plus `.SRCINFO` source-package metadata is configured for CI",
    ),
    ("documentation/release.md", "include-hidden-files: true"),
    (
        "documentation/compatibility.md",
        "tests/checksums.rs::checksum_script_can_include_additional_release_assets",
    ),
    (
        "documentation/compatibility.md",
        "can include `PKGBUILD`, `.SRCINFO`, and `gromaq.install`",
    ),
    (
        "documentation/compatibility.md",
        "Debian `postinst`/`postrm` desktop metadata refresh",
    ),
    (
        "documentation/compatibility.md",
        "Debian package install and payload checks",
    ),
    (
        "README.md",
        "CI run `28309262840` completed green for commit `461006d`",
    ),
    (
        "documentation/release.md",
        "CI run `28309262840` completed green for commit `461006d`",
    ),
    (
        "documentation/compatibility.md",
        "CI run `28309262840` completed green for commit `461006d`",
    ),
    (
        "documentation/compatibility.md",
        "Arch `gromaq.install` desktop metadata refresh",
    ),
    (
        "documentation/compatibility.md",
        "Add live tag-triggered GitHub Release publication proof.",
    ),
    (
        "documentation/compatibility.md",
        "running `scripts/prove-github-release-install.sh` after tagged assets exist.",
    ),
    (
        "documentation/compatibility.md",
        "scripts/prove-github-release-install.sh",
    ),
    (
        "documentation/compatibility.md",
        "Add live Linux desktop menu UI discovery proof.",
    ),
    (
        "documentation/compatibility.md",
        "Add live desktop OS paste-menu workflow proof.",
    ),
    (
        "documentation/compatibility.md",
        "Add Developer ID signed and notarized macOS app distribution proof.",
    ),
    ("documentation/release.md", "28301610408"),
    ("README.md", "28308158338"),
    ("documentation/release.md", "28308158338"),
    ("documentation/compatibility.md", "28308158338"),
    ("documentation/compatibility.md", "28301610408"),
];

pub(super) const REQUIRED_README_COMPLETION_GAP_MARKERS: &[&str] = &[
    "live desktop OS paste-menu workflow",
    "hardware-backed 144 Hz frame pacing proof on a 144 Hz-capable display",
    "live desktop screenshot proof across supported platforms",
    "live tag-triggered GitHub Release asset publication",
    "live Linux release-method install from GitHub Release assets",
    "live Linux desktop menu UI discovery",
    "wider compatibility matrix coverage across shells, editors, multiplexers",
    "Developer ID signed/notarized macOS app distribution",
];
