//! Built-in tmux action catalog.

use super::{ActionId, TmuxAction, action};

pub(super) const ACTIONS: &[TmuxAction] = &[
    action(
        ActionId::StartSession,
        "start-session",
        "Start session",
        "Start a named tmux session.",
        "tmux new-session -s <session>",
        None,
        false,
        false,
        false,
        true,
    ),
    action(
        ActionId::AttachSession,
        "attach-session",
        "Attach session",
        "Attach to an existing tmux session.",
        "tmux attach-session -t <session>",
        None,
        false,
        false,
        false,
        true,
    ),
    action(
        ActionId::DetachSession,
        "detach-session",
        "Detach session",
        "Detach the current tmux client.",
        "tmux detach-client",
        Some("Ctrl-b d"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::SplitPaneRight,
        "split-pane-right",
        "Split pane right",
        "Split the active pane into left and right panes.",
        "tmux split-window -h",
        Some("Ctrl-b %"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::SplitPaneDown,
        "split-pane-down",
        "Split pane down",
        "Split the active pane into top and bottom panes.",
        "tmux split-window -v",
        Some("Ctrl-b \""),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::NewWindow,
        "new-window",
        "New window",
        "Create a new tmux window.",
        "tmux new-window",
        Some("Ctrl-b c"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::RenameSession,
        "rename-session",
        "Rename session",
        "Rename the current or selected session.",
        "tmux rename-session -t <session> <name>",
        Some("Ctrl-b $"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::RenameWindow,
        "rename-window",
        "Rename window",
        "Rename the current or selected window.",
        "tmux rename-window -t <target> <name>",
        Some("Ctrl-b ,"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::NextWindow,
        "next-window",
        "Next window",
        "Select the next tmux window.",
        "tmux next-window",
        Some("Ctrl-b n"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::PreviousWindow,
        "previous-window",
        "Previous window",
        "Select the previous tmux window.",
        "tmux previous-window",
        Some("Ctrl-b p"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::ZoomPane,
        "zoom-pane",
        "Zoom pane",
        "Toggle zoom for the active pane.",
        "tmux resize-pane -Z",
        Some("Ctrl-b z"),
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::SelectPane,
        "select-pane",
        "Select pane",
        "Select a pane by target.",
        "tmux select-pane -t <pane>",
        None,
        false,
        false,
        true,
        false,
    ),
    action(
        ActionId::KillPane,
        "kill-pane",
        "Kill pane",
        "Kill a selected pane.",
        "tmux kill-pane -t <pane>",
        Some("Ctrl-b x"),
        true,
        true,
        true,
        false,
    ),
    action(
        ActionId::KillWindow,
        "kill-window",
        "Kill window",
        "Kill a selected window.",
        "tmux kill-window -t <window>",
        Some("Ctrl-b &"),
        true,
        true,
        true,
        false,
    ),
    action(
        ActionId::KillSession,
        "kill-session",
        "Kill session",
        "Kill a selected session.",
        "tmux kill-session -t <session>",
        None,
        true,
        true,
        true,
        false,
    ),
    action(
        ActionId::ShowHelp,
        "show-help",
        "Show help",
        "Show tmux key bindings and help.",
        "tmux list-keys",
        Some("Ctrl-b ?"),
        false,
        false,
        true,
        true,
    ),
];
